import warp as wp
from warp_ipc.utils.matrix import COOMatrix3x3
from warp_ipc.utils.wp_types import vec12d

@wp.struct
class SimDataDevice:
    X: wp.array(dtype=wp.vec3d)
    x: wp.array(dtype=wp.vec3d)
    surf_vi: wp.array(dtype=wp.int32)
    xt: wp.array(dtype=wp.vec3d)
    edge: wp.array(dtype=wp.vec2i)
    face: wp.array(dtype=wp.vec3i)
    tets: wp.array(dtype=wp.vec4i)
    soft_shell_IB: wp.array(dtype=wp.mat22d)
    soft_shell_E: wp.array(dtype=wp.float64)
    soft_shell_nu: wp.array(dtype=wp.float64)
    soft_shell_elem_vol: wp.array(dtype=wp.float64)
    soft_tet_E: wp.array(dtype=wp.float64)
    soft_tet_nu: wp.array(dtype=wp.float64)
    soft_tet_IB: wp.array(dtype=wp.mat33d)
    soft_tet_elem_vol: wp.array(dtype=wp.float64)
    arap_stretch_k: wp.array(dtype=wp.float64)
    arap_compression_k: wp.array(dtype=wp.float64)
    edge_stretching_stiffness: wp.array(dtype=wp.float64)
    bending: wp.array(dtype=wp.vec4i)
    bending_rest_angle: wp.array(dtype=wp.float64)
    bending_e: wp.array(dtype=wp.float64)
    bending_h: wp.array(dtype=wp.float64)
    bending_stiffness: wp.array(dtype=wp.float64)
    stitch: wp.array(dtype=wp.vec2i)
    stitch_map: wp.array2d(dtype=wp.int32)
    stitch_num_per_x: wp.array(dtype=wp.int32)
    hat_x: wp.array(dtype=wp.vec3d)
    v_x: wp.array(dtype=wp.vec3d)
    a_x: wp.array(dtype=wp.vec3d)
    fn_x: wp.array(dtype=wp.vec3d)
    ft_x: wp.array(dtype=wp.vec3d)
    node_area: wp.array(dtype=wp.float64)
    edge_area: wp.array(dtype=wp.float64)
    node_xi: wp.array(dtype=wp.float64)
    edge_xi: wp.array(dtype=wp.float64)
    face_xi: wp.array(dtype=wp.float64)
    vol_body: wp.array(dtype=wp.float64)
    mass_body: wp.array(dtype=wp.float64)
    soft_tilde_x: wp.array(dtype=wp.vec3d)
    y: wp.array(dtype=wp.vec(length=12, dtype=wp.float64))
    hat_y: wp.array(dtype=wp.vec(length=12, dtype=wp.float64))
    v_y: wp.array(dtype=wp.vec(length=12, dtype=wp.float64))
    a_y: wp.array(dtype=wp.vec(length=12, dtype=wp.float64))
    tilde_y: wp.array(dtype=wp.vec(length=12, dtype=wp.float64))
    affine_ext_force_field: wp.array(dtype=wp.vec3d)
    affine_ext_y_force: wp.array(dtype=vec12d)
    ABD_centers: wp.array(dtype=wp.vec3d)
    node2env: wp.array(dtype=wp.int32)
    edge2env: wp.array(dtype=wp.int32)
    face2env: wp.array(dtype=wp.int32)
    node2body: wp.array(dtype=wp.int32)
    face2body: wp.array(dtype=wp.int32)
    edge2body: wp.array(dtype=wp.int32)
    body_is_affine: wp.array(dtype=wp.int32)
    body_enable_self_collision: wp.array(dtype=wp.int32)
    body_env_id: wp.array(dtype=wp.int32)
    body_collision_layer: wp.array(dtype=wp.int64)
    collision_layer_filter: wp.array(dtype=wp.int64)
    env_states: wp.array(dtype=wp.int32)
    tet_envs: wp.array(dtype=wp.int32)
    E_body: wp.array(dtype=wp.float64)
    nu_body: wp.array(dtype=wp.float64)
    mu_body: wp.array(dtype=wp.float64)
    affine_mass_matrix: wp.array(dtype=wp.mat44d)
    affine_is_closed: wp.array(dtype=wp.int32)
    affine_flipped: wp.array(dtype=wp.int32)
    affine_mass_xi: wp.array(dtype=wp.float64)
    affine_density: wp.array(dtype=wp.float64)
    soft_verts_mass: wp.array(dtype=wp.float64)
    half_space_n: wp.array(dtype=wp.vec3d)
    half_space_o: wp.array(dtype=wp.vec3d)
    half_space_mu: wp.array(dtype=wp.float64)
    hess_affine_diag: COOMatrix3x3
    hess_soft_diag: COOMatrix3x3
    hess_soft_shell_elastic: COOMatrix3x3
    hess_soft_bending_elastic: COOMatrix3x3
    hess_stitch: COOMatrix3x3
    hess_soft_vol_elastic: COOMatrix3x3
    hess_barrier: COOMatrix3x3
    hess_friction: COOMatrix3x3

@wp.struct
class SimCacheDevice:
    soft_shell_energy: wp.array(dtype=wp.float64)
    soft_tet_energy: wp.array(dtype=wp.float64)
    soft_vert_energy: wp.array(dtype=wp.float64)
    affine_body_energy: wp.array(dtype=wp.float64)
    edge_energy: wp.array(dtype=wp.float64)
    vert_energy: wp.array(dtype=wp.float64)
    affine_gradient_y: wp.array(dtype=vec12d)
    soft_gradient_x: wp.array(dtype=wp.vec3d)
    sys_gradient: wp.array(dtype=wp.vec3d)
    direction_x: wp.array(dtype=wp.vec3d)
    sys_direction: wp.array(dtype=wp.vec3d)
    cg_Ap: wp.array(dtype=wp.vec3d)
    cg_diag_inv: wp.array(dtype=wp.mat33d)
    cg_p: wp.array(dtype=wp.vec3d)
    cg_q: wp.array(dtype=wp.vec3d)
    cg_r: wp.array(dtype=wp.vec3d)
    cg_inner_tmp: wp.array(dtype=wp.float64)
    cg_inner_ApTp: wp.array(dtype=wp.float64)
    cg_zTrk: wp.array(dtype=wp.float64)
    cg_zTrk_last: wp.array(dtype=wp.float64)
    cg_alpha: wp.array(dtype=wp.float64)
    cg_beta: wp.array(dtype=wp.float64)
    cg_tol: wp.array(dtype=wp.float64)
    cg_residual: wp.array(dtype=wp.float64)
    cg_solved: wp.array(dtype=wp.bool)
    env_alphas: wp.array(dtype=wp.float64)
    inv_free_alphas: wp.array(dtype=wp.float64)
    damping_sys_energy: wp.array(dtype=wp.float64)
    damping_sys_v: wp.array(dtype=wp.vec3d)
    damping_sys_Hv: wp.array(dtype=wp.vec3d)
    env_newton_iters: wp.array(dtype=wp.int32)
    env_newton_max_iters: wp.array(dtype=wp.int32)